### ISSUE TITLE
Authentication fails after update to 0.7.0 (works again after downgrade to 0.6.2)

### ISSUE THREAD

**Issue by gps1539** [bimmerconnected/bimmer_connected#153]
**Describe the issue**
After updating to 0.7.0 I can no longer authenticate with BMW server
pip3 install bimmer-connected -U
``python -m bimmer_connected.cli lightflash gps1539@gmail.com passwd north_america VIN
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:getting new oauth token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): customer.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://customer.bmwgroup.com:443 "POST /gcdm/usa/oauth/authenticate HTTP/1.1" 302 None
DEBUG:bimmer_connected.account:got new token axGA7phqTMa6ouuK6r4ih8lecoi6ZCml with expiration date 2020-02-17 22:26:19.763632
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.us:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.us:443 "GET /webapi/v1/user/vehicles HTTP/1.1" 401 0
DEBUG:bimmer_connected.account:The BMW Connected Drive portal returned an error: UNAUTHORIZED (received status code 401 and expected 200).
DEBUG:bimmer_connected.account:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/bimmer_connected/cli.py", line 150, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/bimmer_connected/cli.py", line 60, in main
    args.func(args)
  File "/usr/lib/python3.8/site-packages/bimmer_connected/cli.py", line 103, in light_flash
    account = ConnectedDriveAccount(args.username, args.password, get_region_from_name(args.region))
  File "/usr/lib/python3.8/site-packages/bimmer_connected/account.py", line 61, in __init__
    self._get_vehicles()
  File "/usr/lib/python3.8/site-packages/bimmer_connected/account.py", line 209, in _get_vehicles
    response = self.send_request(VEHICLES_URL.format(server=self.server_url), headers=self.request_header,
  File "/usr/lib/python3.8/site-packages/bimmer_connected/account.py", line 152, in send_request
    raise IOError(msg)
OSError: The BMW Connected Drive portal returned an error: UNAUTHORIZED (received status code 401 and expected `200).`

After downgrading to 0.6.2 the status is reported correctly.

Running python 3.8.1

**Expected behavior**
Status is correctly returned

**Home Assistant version**
Not using HA

**Comment by rikroe** [comment]
Damn! They only changed rest_of_world servers, US (and probably China too) are apparently using the old API.
PR incoming!
