### ISSUE TITLE
KeyError: 'vehicleStatus' with 0.70.0 / HA 0.105.5

### ISSUE THREAD

**Issue by m0wlheld** [bimmerconnected/bimmer_connected#154]
**Describe the issue**
Home Assistant 0.105.5 integrated 0.70.0 to address an API change at BMW. However, the integration still fails to connect: 

See my HA issue at https://github.com/home-assistant/home-assistant/issues/31940

**Expected behavior**
Connect to BMW connected drive services and offer car data and actions in Home Assistant.

**Home Assistant version**
Which Home Assistant version are you using. And did it work on a previous version, if so what was the last working version.

Currently: 0.105.5
Last Working: 0.105.3 (but then BMW changed their API)

**Screenshots**
No screenshots taken

**Your config.yaml**
```yaml
bmw_connected_drive:
  mycar:
    username: !secret bmw_connected_drive_username
    password: !secret bmw_connected_drive_password
    region: "rest_of_world"
````

**Output of bimmer_connected fingerprint**
bimmer_connected did not complete, but returns an error by itself:

```txt
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:getting new oauth token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): customer.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://customer.bmwgroup.com:443 "POST /gcdm/oauth/authenticate HTTP/1.1" 302 None
DEBUG:bimmer_connected.account:got new token ********************** with expiration date 2020-02-18 09:20:13.203154
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles HTTP/1.1" 200 None
DEBUG:bimmer_connected.state:requesting new data from connected drive
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles/WBAJXXXXXXXXXXXXX/status?deviceTime=2020-02-18T07%3A20%3A15&dlat=0.0&dlon=0.0 HTTP/1.1" 500 None
DEBUG:bimmer_connected.account:Error 500 on attempt 1
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles/WBAJXXXXXXXXXXXXX/status?deviceTime=2020-02-18T07%3A20%3A15&dlat=0.0&dlon=0.0 HTTP/1.1" 500 None
DEBUG:bimmer_connected.account:Error 500 on attempt 2
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles/WBAJXXXXXXXXXXXXX/status?deviceTime=2020-02-18T07%3A20%3A15&dlat=0.0&dlon=0.0 HTTP/1.1" 500 None
DEBUG:bimmer_connected.account:Error 500 on attempt 3
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles/WBAJXXXXXXXXXXXXX/status?deviceTime=2020-02-18T07%3A20%3A15&dlat=0.0&dlon=0.0 HTTP/1.1" 500 None
DEBUG:bimmer_connected.account:Error 500 on attempt 4
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles/WBAJXXXXXXXXXXXXX/status?deviceTime=2020-02-18T07%3A20%3A15&dlat=0.0&dlon=0.0 HTTP/1.1" 500 None
DEBUG:bimmer_connected.account:Error 500 on attempt 5
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles/WBAJXXXXXXXXXXXXX/status?deviceTime=2020-02-18T07%3A20%3A15&dlat=0.0&dlon=0.0 HTTP/1.1" 500 None
DEBUG:bimmer_connected.account:Error 500 on attempt 6
Traceback (most recent call last):
  File "/usr/bin/bimmerconnected", line 11, in <module>
    load_entry_point('bimmer-connected==0.7.0', 'console_scripts', 'bimmerconnected')()
  File "/usr/lib/python3.8/site-packages/bimmer_connected/cli.py", line 60, in main
    args.func(args)
  File "/usr/lib/python3.8/site-packages/bimmer_connected/cli.py", line 96, in fingerprint
    account.update_vehicle_states()
  File "/usr/lib/python3.8/site-packages/bimmer_connected/account.py", line 233, in update_vehicle_states
    car.update_state()
  File "/usr/lib/python3.8/site-packages/bimmer_connected/vehicle.py", line 122, in update_state
    self.state.update_data()
  File "/usr/lib/python3.8/site-packages/bimmer_connected/state.py", line 131, in update_data
    attributes = response.json()['vehicleStatus']
KeyError: 'vehicleStatus'
````

*NOTE: It might take me a while to respond on GitHub (I only maintain this in my free time), but I will respond.*

**Comment by gerard33** [comment]
What is the type and year of your car?

Are you able to run `fingerprint` as mentioned [here](https://github.com/bimmerconnected/bimmer_connected#data-contributions)?

**Comment by m0wlheld** [comment]
> What is the type and year of your car?

BMW 530e iPerformance, production date 2019-11-07

> Are you able to run `fingerprint` as mentioned [here](https://github.com/bimmerconnected/bimmer_connected#data-contributions)?

Tried that, but it reported the error quoted in the issue report.

**Comment by gerard33** [comment]
Nice car :+1:

I suspected that it could be caused by 'old' cars that don't contain much data, but that's certainly not the case with your car.

Maybe @rikroe can have a look at this to see if it is linked to #151 (or otherwise we have to check #149 as that is part of `0.7.0` as well).

**Comment by m0wlheld** [comment]
Actually, the issue is gone. Just restarted Home Assistant once again and the BMW Connected Drive integration comes up with no errors. 

Maybe a temporary problem this morning. 

I close this, not reproducable. Thanks for your feedback.

**Comment by m0wlheld** [comment]
Sorry, the error is back, just know. Although I think that the Connected Drive Service is f*cked again, you might want to take a look. 

Not re-opening, though. 

```
Wed Feb 19 2020 07:26:07 GMT+0100 (CET)

'vehicleStatus'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 58, in _update_all
    cd_account.update()
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 142, in update
    self.account.update_vehicle_states()
  File "/usr/local/lib/python3.7/site-packages/bimmer_connected/account.py", line 233, in update_vehicle_states
    car.update_state()
  File "/usr/local/lib/python3.7/site-packages/bimmer_connected/vehicle.py", line 122, in update_state
    self.state.update_data()
  File "/usr/local/lib/python3.7/site-packages/bimmer_connected/state.py", line 131, in update_data
    attributes = response.json()['vehicleStatus']
KeyError: 'vehicleStatus'
```

**Comment by whitwocb** [comment]
Hi all,

I get this error since maybe 4 or 5 days or so:


2020-04-18 11:33:28 ERROR (MainThread) [homeassistant.setup] Error during setup of component bmw_connected_drive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 175, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 51, in setup
    accounts.append(setup_account(account_config, hass, name))
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 79, in setup_account
    cd_account = BMWConnectedDriveAccount(username, password, region, name, read_only)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 126, in __init__
    self.account = ConnectedDriveAccount(username, password, region)
  File "/usr/local/lib/python3.7/site-packages/bimmer_connected/account.py", line 61, in __init__
    self._get_vehicles()
  File "/usr/local/lib/python3.7/site-packages/bimmer_connected/account.py", line 230, in _get_vehicles
    for vehicle_dict in response.json()['vehicles']:
KeyError: 'vehicles'


Not sure if this is the right place to post this? Please let me know if not..

**Comment by gerard33** [comment]
@whitwocb please make an issue here -> https://github.com/bimmerconnected/bimmer_connected/issues/new?assignees=&labels=&template=issue-template.md&title= so we have all needed details to investigate the issue.
