### ISSUE TITLE
BMW Connected Drive broken after HA upgrade to 

### ISSUE THREAD

**Issue by jsimon3** [bimmerconnected/bimmer_connected#180]
Upgraded to 0.110 which broke the Connected Drive integration. This was working fine until the upgrade from 0.109. 

Errors below:

2020-05-21 14:33:34 ERROR (MainThread) [homeassistant.setup] Error during setup of component bmw_connected_drive
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xaee86970>: Failed to establish a new connection: [Errno 111] Connection refused

**Comment by rikroe** [comment]
This is rather an issue within Home Assistant/your setup. 
There been no changes to the library or the integration and it continues to work for me on 110.

How is your HA installed?

The "Connection refused" is a message that I've seen before when having proxy server issues.

**Comment by jsimon3** [comment]
Hi there,

 �

First of all, thank you for your prompt response, much appreciated.

 �

I am running a Hass.io image on a Raspberry 4. There is no Proxy. There was no other integration that seemed to have issues, but truth be told I didn’t look very hard. At least the log file showed no other issues besides the BMW Connected Drive.

 �

After I downgraded back to 0.109, the connection was working again and all sensors were getting data.

 �

Is there a server I can ping or traceroute from the raspberry to rule out that connectivity is not the issue ? 

 �

Jan

 �

**Comment by rikroe** [comment]
You can find the respective urls in `const.py` and `country_selector.py`. 
Although my guess is that something didn't work out with the update, have you tried in again?

**Comment by jsimon3** [comment]
Hi,

Just tried upgrading again and this time it worked. Everything is up and running without errors including the BMW sensors.

Many thanks,

Jan

**Comment by rikroe** [comment]
Glad that it works! :) 
Closing this issue.
