### ISSUE TITLE
ValueError when running bimmerconnected

### ISSUE THREAD

**Issue by pomputer** [bimmerconnected/bimmer_connected#195]
**Describe the issue**
When I run `bimmerconnected` with or without any arguments, I get this error:
`Traceback (most recent call last):
  File "/usr/local/bin/bimmerconnected", line 6, in <module>
    from bimmer_connected.cli import main
  File "/usr/local/lib/python3.7/dist-packages/bimmer_connected/cli.py", line 12, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 44, in <module>
    import chardet
  File "/usr/lib/python3/dist-packages/chardet/__init__.py", line 20, in <module>
    from .universaldetector import UniversalDetector
  File "/usr/lib/python3/dist-packages/chardet/universaldetector.py", line 47, in <module>
    from .mbcsgroupprober import MBCSGroupProber
  File "/usr/lib/python3/dist-packages/chardet/mbcsgroupprober.py", line 32, in <module>
    from .sjisprober import SJISProber
  File "/usr/lib/python3/dist-packages/chardet/sjisprober.py", line 30, in <module>
    from .chardistribution import SJISDistributionAnalysis
  File "/usr/lib/python3/dist-packages/chardet/chardistribution.py", line 30, in <module>
    from .euckrfreq import (EUCKR_CHAR_TO_FREQ_ORDER, EUCKR_TABLE_SIZE,
ValueError: source code string cannot contain null`

It worked before on the same version (0.7.7)
I don't think this needs any more explaining :D, so I will leave it here.

**Comment by gerard33** [comment]
Looks like something strange happened on your machine with requests, chardet or universaldetector.
The error is not caused by `bimmerconnected` as you also mention that it worked before with the same version.

Please try to install `bimmerconnected` on a clean environment and you will see that it still works.

**Comment by pomputer** [comment]
I just reinstalled chardet and now it works. Thanks anyway!
