### ISSUE TITLE
BMW connective drive not working after updating to 117.3

### ISSUE THREAD

**Issue by renjithstalin** [bimmerconnected/bimmer_connected#232]
**Describe the issue**
Error during setup of component bmw_connected_drive, getting this error after updating to 117.3. This is one of my favorite components and as far I remember, the BMW component never failed.
A clear and concise description of what the issue is.

**Expected behavior**

**Home Assistant version (if used)**

Which Home Assistant version are you using?
117.3
And did it work on a previous version, if so what was the last working version?
It was super stable on all previous versions.
**Screenshots**

2020-11-04 10:33:14 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration vesync to set up vesync configuration entry: No module named 'custom_components.vesync.config_flow'
2020-11-04 10:33:14 ERROR (MainThread) [homeassistant.setup] Error during setup of component bmw_connected_drive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 52, in setup
    accounts.append(setup_account(account_config, hass, name))
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 80, in setup_account
    cd_account = BMWConnectedDriveAccount(username, password, region, name, read_only)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 127, in __init__
    self.account = ConnectedDriveAccount(username, password, region)
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/account.py", line 61, in __init__
    self._get_vehicles()
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/account.py", line 215, in _get_vehicles
    response = self.send_request(VEHICLES_URL.format(server=self.server_url), headers=self.request_header,
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/account.py", line 152, in send_request
    raise IOError(msg)
OSError: The BMW Connected Drive portal returned an error: UNAUTHORIZED (received status code 401 and expected 200).
2020-11-04 10:33:15 ERROR (MainThread) [homeassistant.components.media_player] Platform samsungtv does not generate unique IDs. ID e8f67932-8016-4dae-acad-8399ffc4aa4a already exists - ignoring media_player.samsung_un40ku6300
2020-11-04 10:33:15 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140291310163088] Error handling message: Unknown error
Traceback (most recent call last):

OSError: The BMW Connected Drive portal returned an error: UNAUTHORIZED (received status code 401 and expected 200).
**ConnectedDrive website**

If you see any issues with the BMW integration in Home Assistant (or when directly using the library), please make sure to first login to the BMW ConnectedDrive website of your country and check if you can successfully login and query the car status.
- [ X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [ ] I have ConnectedDrive enabled for my vehicle.

**Your config.yaml**

```yaml
bmw_connected_drive:
  name:
    username: !secret bmw_username
    password: !secret bmw_passwd
    region: north_america
````

**Number of cars**

If you have more than 1 car please mention that here.
- [X ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

**Output of bimmer_connected fingerprint**

If you have run the [bimmer_connected fingerprint](https://github.com/bimmerconnected/bimmer_connected#data-contributions) please share that data here

*NOTE: It might take us a while to respond on GitHub (we only maintain this in our free time), but we will respond.*
Sorry! not sure what this is..

**Comment by rikroe** [comment]
Hey, while fixing the login for rest_of_world and china, we broke north_america.
Unfortunately, the APIs on BMW side seem a bit unstable and reverse engineering is a pain.

Downgrading to 0.117.2 should be a workaround for now and we'll see that it is adressed in the next update.

**Comment by renjithstalin** [comment]
Downgraded my instance to 11.2 and life is back to normal. Thank you so very much, for the prompt support. 👍

**Comment by rikroe** [comment]
Reopening this until it gets fixed
