### ISSUE TITLE
Getting the error  "received status code 400 and expected 200" when trying to log in using a Mini.

### ISSUE THREAD

**Issue by scstraus** [bimmerconnected/bimmer_connected#255]
**Describe the issue**

Getting the error  "received status code 400 and expected 200" when trying to log in. Looks like same behavior as in [this previous issue](https://github.com/bimmerconnected/bimmer_connected/issues/100)

**Expected behavior**

For it to log in and recieve the data ;-)

**Home Assistant version (if used)**

.117.7

Was working until .116.6, and I thought until a few days ago. I drove the car today and none of the sensors updated, then when I restarted I got the error. The login hasn't changed and I was able to log in to the Mini mobile app with the same credentials and it works fine.

**Screenshots**

**ConnectedDrive website**

If you see any issues with the BMW integration in Home Assistant (or when directly using the library), please make sure to first login to the BMW ConnectedDrive website of your country and check if you can successfully login and query the car status.
- [ ] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
(I have a mini. I can log into the bmw connected drive website, but it asks me to add a VIN and from that VIN it tells me that only BMW branded vehicles can be used there, however, the Mini Connected app works fine with these credentials)
- [X ] I have ConnectedDrive enabled for my vehicle.

**Your config.yaml**

```yaml
bmw_connected_drive:
  name: 
    username: !secret mini_uname
    password: !secret mini_pw
    region: rest_of_world
````

**Number of cars**

If you have more than 1 car please mention that here.
- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ X] I have a Mini vehicle linked to my account.

**Output of bimmer_connected fingerprint**

If you have run the [bimmer_connected fingerprint](https://github.com/bimmerconnected/bimmer_connected#data-contributions) please share that data here

I haven't done this, but can if needed.

*NOTE: It might take us a while to respond on GitHub (we only maintain this in our free time), but we will respond.*

**Log Output**

```
Logger: homeassistant.setup
Source: components/bmw_connected_drive/__init__.py:127
First occurred: 11:12:33 PM (1 occurrences)
Last logged: 11:12:33 PM
Error during setup of component bmw_connected_drive

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/account.py", line 98, in _get_oauth_token
    response = self.send_request(url, data=data, headers=headers, allow_redirects=False,
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/account.py", line 152, in send_request
    raise IOError(msg)
OSError: The BMW Connected Drive portal returned an error: UNKNOWN_ERROR (received status code 400 and expected 200).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 52, in setup
    accounts.append(setup_account(account_config, hass, name))
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 80, in setup_account
    cd_account = BMWConnectedDriveAccount(username, password, region, name, read_only)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 127, in __init__
    self.account = ConnectedDriveAccount(username, password, region)
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/account.py", line 61, in __init__
    self._get_vehicles()
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/account.py", line 214, in _get_vehicles
    self._get_oauth_token()
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/account.py", line 104, in _get_oauth_token
    raise OSError(msg) from exception
OSError: Authentication failed. Maybe your password is invalid?
```

**Comment by scstraus** [comment]
Argh, just found the other ticket that was closed yesterday.. I googled the exact error and looked at open tickets and came up with nothing.
