### ISSUE TITLE
Key errors (chargingInductivePositioning, fuelPercent)

### ISSUE THREAD

**Issue by fredericks1982** [bimmerconnected/bimmer_connected#257]
### Describe the issue ###
I'm using Home Assistant and during startup of BMW Connected Drive component I get the errors `KeyError: 'chargingInductivePositioning'` and `KeyError: 'fuelPercent'`. These errors don't prevent the component to start and other values are properly reported.
I've opened a similar [issue on Home Assistant repository](https://github.com/home-assistant/core/issues/43807), but maybe it could be a bug on this library ...so here I am!

### Expected behavior ###
No errors on Home Assistant's BMW Connected Drive component startup.

### Home Assistant version (if used) ###
- Which Home Assistant version are you using? **0.118.4**
- And did it work on a previous version, if so what was the last working version? N/A

### ConnectedDrive website ###

If you see any issues with the BMW integration in Home Assistant (or when directly using the library), please make sure to first login to the BMW ConnectedDrive website of your country and check if you can successfully login and query the car status.
- [x] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [x] I have ConnectedDrive enabled for my vehicle.

### Your config.yaml ###

```yaml
bmw_connected_drive:
  name:
    username: !secret mini_username
    password: !secret mini_password
    region: 'rest_of_world'
````

### Home Assistant logs ###
```
2020-12-01 09:31:29 ERROR (MainThread) [homeassistant.components.sensor] bmw_connected_drive: Error on device update!,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity,
    await entity.async_device_update(warning=False),
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update,
    await task,
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/sensor.py", line 154, in update,
    self._state = getattr(vehicle_state, self._attribute),
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/state.py", line 125, in __getattr__,
    return self.vehicle_status.attributes[item],
KeyError: 'chargingInductivePositioning',
2020-12-01 09:31:29 ERROR (MainThread) [homeassistant.components.sensor] bmw_connected_drive: Error on device update!,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity,
    await entity.async_device_update(warning=False),
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update,
    await task,
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/sensor.py", line 154, in update,
    self._state = getattr(vehicle_state, self._attribute),
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/state.py", line 125, in __getattr__,
    return self.vehicle_status.attributes[item],
KeyError: 'fuelPercent',
```

### Number of cars ###

If you have more than 1 car please mention that here.
- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [x] I have a Mini vehicle linked to my account. Car is a brand new **Mini Cooper S E Countryman All4**.

**Comment by rikroe** [comment]
Could you please provide a [vehicle fingerprint](https://bimmer-connected.readthedocs.io/en/latest/#data-contributions)? 
That would make debugging the issue simpler.

Many thanks!

**Comment by fredericks1982** [comment]
Here you are my [vehicle_fingerprint.zip](https://github.com/bimmerconnected/bimmer_connected/files/5624243/vehicle_fingerprint.zip). Thanks for your support!

**Comment by plourenco** [comment]
It seems like they are no longer sending `chargingInductivePositioning` and `fuelPercent`. The same happens in a BMW 330e. Can anyone else confirm?

**Comment by nilsvdb82** [comment]
My BMW X5 45e still returns fuelpercent.
However, chargingInductivePostioning seems removed

**Comment by dgomes** [comment]
Not fixed as of 2021.01:

```txt
2021-01-11 01:05:58 ERROR (MainThread) [homeassistant.components.sensor] bmw_connected_drive: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/sensor.py", line 136, in update
    self._state = getattr(vehicle_state, self._attribute)
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/state.py", line 125, in __getattr__
    return self.vehicle_status.attributes[item]
KeyError: 'chargingInductivePositioning'
2021-01-11 01:05:58 ERROR (MainThread) [homeassistant.components.sensor] bmw_connected_drive: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/sensor.py", line 136, in update
    self._state = getattr(vehicle_state, self._attribute)
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/state.py", line 125, in __getattr__
    return self.vehicle_status.attributes[item]
KeyError: 'fuelPercent'
```

**Comment by rikroe** [comment]
Thanks for pointing this out, will have a look at creating a upstream release and updating the dependency.

**Comment by rikroe** [comment]
Still open as we need a new release. Just waiting for #262 to be merged as well.
