### ISSUE TITLE
Unable to authenticate after HA update

### ISSUE THREAD

**Issue by jackshaw20** [bimmerconnected/bimmer_connected#281]
Hi,

I have updated HA and after a reboot I am now getting authentication errors;

Logger: bimmer_connected.account
Source: /usr/local/lib/python3.8/site-packages/bimmer_connected/account.py:107
First occurred: 14:17:13 (8 occurrences)
Last logged: 14:18:00

The BMW Connected Drive portal returned an error: UNKNOWN_ERROR (received status code 502 and expected 200).
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/account.py", line 102, in _get_oauth_token
    response = self.send_request(url, data=data, headers=headers, allow_redirects=False,
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/account.py", line 156, in send_request
    raise IOError(msg)
OSError: The BMW Connected Drive portal returned an error: UNKNOWN_ERROR (received status code 502 and expected 200).

Logger: bimmer_connected.account
Source: /usr/local/lib/python3.8/site-packages/bimmer_connected/account.py:106
First occurred: 14:17:13 (8 occurrences)
Last logged: 14:18:00

Authentication failed. Maybe your password is invalid?

**Comment by jackshaw20** [comment]
I now seem to be getting the status of the vehicle again after another reboot of HA,  but when I send a command to unlock for example I get this error:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/bmw_connected_drive/lock.py:81
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:40:58 (1 occurrences)
Last logged: 16:40:58

[139770789605280] 'executionStatus'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 103, in async_lock
    await self.hass.async_add_executor_job(ft.partial(self.lock, **kwargs))
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bmw_connected_drive/lock.py", line 81, in lock
    self._vehicle.remote_services.trigger_remote_door_lock()
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/remote_services.py", line 159, in trigger_remote_door_lock
    result = self._block_until_done(_Services.REMOTE_DOOR_LOCK)
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/remote_services.py", line 214, in _block_until_done
    status = self._get_remote_service_status(service)
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/remote_services.py", line 237, in _get_remote_service_status
    return RemoteServiceStatus(json_result)
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/remote_services.py", line 119, in __init__
    status = response['executionStatus']
KeyError: 'executionStatus'

**Comment by rikroe** [comment]
I had some of these issues as well but for me it works again - seems BMW is having some hickups with their servers again.
Please check tomorrow (I'll do as well).

**Comment by jackshaw20** [comment]
ok thank you :)

**Comment by jackshaw20** [comment]
I am still getting the error below,  but one on one of the accounts I have connected, the other vehicle on the other account I don't get any errors.    strange thing is I get the execution error but it does actually perform the action;

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/bmw_connected_drive/lock.py:81
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:03:00 (1 occurrences)
Last logged: 21:03:00

[139770613953104] 'executionStatus'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 103, in async_lock
    await self.hass.async_add_executor_job(ft.partial(self.lock, **kwargs))
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bmw_connected_drive/lock.py", line 81, in lock
    self._vehicle.remote_services.trigger_remote_door_lock()
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/remote_services.py", line 159, in trigger_remote_door_lock
    result = self._block_until_done(_Services.REMOTE_DOOR_LOCK)
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/remote_services.py", line 214, in _block_until_done
    status = self._get_remote_service_status(service)
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/remote_services.py", line 237, in _get_remote_service_status
    return RemoteServiceStatus(json_result)
  File "/usr/local/lib/python3.8/site-packages/bimmer_connected/remote_services.py", line 119, in __init__
    status = response['executionStatus']
KeyError: 'executionStatus'

**Comment by rikroe** [comment]
Thats probably because you are using the custom component. It was fixed in HA with HA 2021.3.0 through https://github.com/home-assistant/core/pull/47066 (bumping bimmer_connected to 0.7.15).

We didn't upgrade the custom component though.
