### ISSUE TITLE
Stopped working again

### ISSUE THREAD

**Issue by rhoddan** [bimmerconnected/bimmer_connected#311]
### Describe the issue

Since 8 hours ago the service stopped work (no sensor updates or no service)

### Expected behavior

be able to get data and send service commands

### Which Home Assistant version are you using?

core-2021.8.6

### What was the last working version of Home Assistant Core?

core-2021.8.6

### What is your region?

Rest of world

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Where are you located? `rest_of_world` works for me.
Can you provide the output of `bimmerconnected status ...`?

**Comment by rhoddan** [comment]
Sweden (rest_of_world)
![Screenshot 2021-08-13 103049](https://user-images.githubusercontent.com/33499995/129330598-78bdd04d-1498-4f44-9f81-4333bc7442e5.png)

  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 239, in execute_service
    function_call()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/remote_services.py", line 196, in trigger_remote_air_conditioning
    self._trigger_remote_service(_Services.REMOTE_AIR_CONDITIONING, post=True)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/remote_services.py", line 209, in _trigger_remote_service
    return self._account.send_request(url, post=post, data=data)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 213, in send_request
    raise IOError(msg)
OSError: The BMW Connected Drive portal returned an error: UNKNOWN_ERROR (received status code 400 and expected 200).
2021-08-13 10:27:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [xxx] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/__init__.py", line 239, in execute_service
    function_call()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/remote_services.py", line 196, in trigger_remote_air_conditioning
    self._trigger_remote_service(_Services.REMOTE_AIR_CONDITIONING, post=True)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/remote_services.py", line 209, in _trigger_remote_service
    return self._account.send_request(url, post=post, data=data)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 213, in send_request
    raise IOError(msg)
OSError: The BMW Connected Drive portal returned an error: UNKNOWN_ERROR (received status code 400 and expected 200).
2021-08-13 10:29:17 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [xxx] The BMW Connected Drive portal returned an error: UNKNOWN_ERROR (received status code 400 and expected 200).
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 149, in async_unlock
    await self.hass.async_add_executor_job(ft.partial(self.unlock, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/lock.py", line 56, in unlock
    self._vehicle.remote_services.trigger_remote_door_unlock()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/remote_services.py", line 174, in trigger_remote_door_unlock
    self._trigger_remote_service(_Services.REMOTE_DOOR_UNLOCK, post=True)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/remote_services.py", line 209, in _trigger_remote_service
    return self._account.send_request(url, post=post, data=data)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 213, in send_request
    raise IOError(msg)
OSError: The BMW Connected Drive portal returned an error: UNKNOWN_ERROR (received status code 400 and expected 200).
2021-08-13 10:30:26 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [xxx] The BMW Connected Drive portal returned an error: UNKNOWN_ERROR (received status code 400 and expected 200).
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 141, in async_lock
    await self.hass.async_add_executor_job(ft.partial(self.lock, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/lock.py", line 47, in lock
    self._vehicle.remote_services.trigger_remote_door_lock()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/remote_services.py", line 162, in trigger_remote_door_lock
    self._trigger_remote_service(_Services.REMOTE_DOOR_LOCK, post=True)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/remote_services.py", line 209, in _trigger_remote_service
    return self._account.send_request(url, post=post, data=data)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 213, in send_request
    raise IOError(msg)
OSError: The BMW Connected Drive portal returned an error: UNKNOWN_ERROR (received status code 400 and expected 200).

**Comment by rikroe** [comment]
Ah, yes. Remote services are not yet available again (see https://github.com/home-assistant/core/issues/54524, #310).
Closing this one as it is already tracked.
