### ISSUE TITLE
The `image` command is broken on 0.8.0b6

### ISSUE THREAD

**Issue by rikroe** [bimmerconnected/bimmer_connected#345]
The `image` command is broken:

```
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1636986839.295627&tireGuardMode=ENABLED HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/Users/andig/htdocs/bimmer_connected/bimmer_connected/cli.py", line 285, in <module>
    main()
  File "/Users/andig/htdocs/bimmer_connected/bimmer_connected/cli.py", line 281, in main
    args.func(args)
  File "/Users/andig/htdocs/bimmer_connected/bimmer_connected/cli.py", line 197, in image
    image_data = vehicle.get_vehicle_image(400, 400, VehicleViewDirection.FRONT)
TypeError: get_vehicle_image() takes 2 positional arguments but 4 were given
```

_Originally posted by @andig in https://github.com/bimmerconnected/bimmer_connected/issues/325#issuecomment-969030662_

**Comment by rikroe** [comment]
Should be fixed in [`bimmer_connected==0.8.0b7`](https://github.com/bimmerconnected/bimmer_connected/releases/tag/0.8.0b7).

**Comment by andig** [comment]
It's not:

```
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1637049053.622885&tireGuardMode=ENABLED HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/Users/andig/htdocs/bimmer_connected/bimmer_connected/cli.py", line 283, in <module>
    main()
  File "/Users/andig/htdocs/bimmer_connected/bimmer_connected/cli.py", line 279, in main
    args.func(args)
  File "/Users/andig/htdocs/bimmer_connected/bimmer_connected/cli.py", line 195, in image
    image_data = vehicle.get_vehicle_image(viewdirection)
  File "/opt/homebrew/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 205, in get_vehicle_image
    header['accept'] = 'image/png'
TypeError: 'method' object does not support item assignment
```

**Comment by rikroe** [comment]
Strange, it works for me. Can you please check if your vehicle.py is the same as the lines here?
https://github.com/bimmerconnected/bimmer_connected/blob/mybmw/bimmer_connected/vehicle.py#L186-L200

I'm asking because the line where it breaks for you (L205) is not even part of the current `get_vehicle_image` function.

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cocoapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1637050638.012332&tireGuardMode=ENABLED HTTP/1.1" 200 2
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:bimmer_connected.account:Request to: https://cocoapi.bmwgroup.com/eadrax-ics/v3/presentation/vehicles/VIN/images?carView=VehicleStatus
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cocoapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-ics/v3/presentation/vehicles/VIN/images?carView=VehicleStatus HTTP/1.1" 200 174737
vehicle image saved to frontside.png
```

**Comment by danfulton72** [comment]
It is working for me in 0.8.0b7 👍

**Comment by andig** [comment]
Sorry, didn't realize I needed a 

    pip3 install .

when testing latest git locally. Not a python guy...

**Comment by andig** [comment]
The requests are still strange:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cocoapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1637056448.757379&tireGuardMode=ENABLED HTTP/1.1" 200 2
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:bimmer_connected.account:Request to: https://cocoapi.bmwgroup.com/eadrax-ics/v3/presentation/vehicles/xxx/images?carView=VehicleStatus
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cocoapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-ics/v3/presentation/vehicles/xxx/images?carView=VehicleStatus HTTP/1.1" 200 188190
vehicle image saved to frontside.png
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:bimmer_connected.account:Request to: https://cocoapi.bmwgroup.com/eadrax-ics/v3/presentation/vehicles/xxx/images?carView=VehicleInfo
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cocoapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-ics/v3/presentation/vehicles/xxx/images?carView=VehicleInfo HTTP/1.1" 200 104853
vehicle image saved to front.png
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:bimmer_connected.account:Request to: https://cocoapi.bmwgroup.com/eadrax-ics/v3/presentation/vehicles/xxx/images?carView=ChargingHistory
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cocoapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-ics/v3/presentation/vehicles/xxx/images?carView=ChargingHistory HTTP/1.1" 200 201130
vehicle image saved to side.png
```

What does `VehicleStatus` have to do with a `frontside` image?

**Comment by rikroe** [comment]
> What does `VehicleStatus` have to do with a `frontside` image?

The new API doesn't provide views like front/side/etc. 
I am just reusing the viewpoints used in the car app, where VehicleStatus will give you a front view of your car (because it is displayed in the vehicle status tab of the app). 

Please check images they should be mapped correctly.
