### ISSUE TITLE
Get an error when update the vehicle status in homeassistant

### ISSUE THREAD

**Issue by muxiachuixue** [bimmerconnected/bimmer_connected#373]
### Describe the issue

Sometimes (not every time) when I call the service "bmw_connected_drive.update_state" in homeassistant, it gives me an error: See below.

A restart of HA can solve this problem.

Bimmerconnected version in HA: [0.8.3.0b4](https://github.com/bimmerconnected/ha_custom_component/releases/tag/20211127.1)

Operating_system: Raspbian GNU/Linux 10 (buster)

### Expected behavior

When I call the homeassistant service "bmw_connected_drive.update_state" , it returns no error.

### Which Home Assistant version are you using?

2021.11.5

### What is your region?

China

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/bmw_connected_drive/__init__.py:319
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:46:23 (4 occurrences)
Last logged: 11:50:06

[2718049568] 'status'
[2718049568] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/bmw_connected_drive/__init__.py", line 132, in _async_update_all
    await hass.async_add_executor_job(_update_all)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bmw_connected_drive/__init__.py", line 137, in _update_all
    entry[CONF_ACCOUNT].update()
  File "/config/custom_components/bmw_connected_drive/__init__.py", line 319, in update
    self.account.update_vehicle_states()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 412, in update_vehicle_states
    self._get_vehicles()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 390, in _get_vehicles
    existing_vehicle.update_state(vehicle_dict)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 91, in update_state
    self.status.update_state({k: v for k, v in vehicle_dict.items() if k in [SERVICE_STATUS, SERVICE_PROPERTIES]})
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle_status.py", line 166, in update_state
    self.status: Dict = status_dict["status"]
KeyError: 'status'
```

**Comment by rikroe** [comment]
Thanks for reporting! I'll will try to catch this information and print some error logs.
