### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by licheng5625** [bimmerconnected/bimmer_connected#399]
### Describe the issue

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 363, in state
value = self.native_value
File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/sensor.py", line 173, in native_value
return cast(StateType, self.entity_description.value(state, self.hass))
File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/sensor.py", line 91, in <lambda>
hass.config.units.length(x[0], UNIT_MAP.get(x[1], x[1]))
TypeError: 'NoneType' object is not subscriptable

### Expected behavior

no error ?

### Which Home Assistant version are you using?

Home Assistant 2021.12.8

### What is your region?

Rest of world

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [ ] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [X] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Thanks for reporting! Seems like that if an attribute with a unit (e.g. remaining_range) cannot be parsed, we just return `None` but Home Assistant expects a tuple (e.g. `(None, None)`.
Should be an easy fix.
