### ISSUE TITLE
X3 PHEV | KeyError: 'reductionOfChargeCurrent'

### ISSUE THREAD

**Issue by YeomansIII** [bimmerconnected/bimmer_connected#460]
### Describe the issue

Running bimmer_connected via the Home Assistant integration. The integration started failing and after logging out and attempting to log back in, I am receiving the following error from this library's code. It's possible this Key is no longer present in the BMW API?

KeyError: 'reductionOfChargeCurrent'

### Expected behavior

Integration should log in and work with no key errors.

### Which Home Assistant version are you using?

Home Assistant Core 2022.6.6

### What is your region?

North America

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Anything in the logs that might be useful for us?

```txt
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
home-assistant   |     resp = await request_handler(request)
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
home-assistant   |     resp = await handler(request)
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
home-assistant   |     result = await result
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
home-assistant   |     return await super().post(request, flow_id)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
home-assistant   |     result = await method(view, request, *args, **kwargs)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
home-assistant   |     result = await self._flow_mgr.async_configure(flow_id, data)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
home-assistant   |     result = await self._async_handle_step(
home-assistant   |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
home-assistant   |     result: FlowResult = await getattr(flow, method)(user_input)
home-assistant   |   File "/config/custom_components/bmw_connected_drive/config_flow.py", line 68, in async_step_user
home-assistant   |     info = await validate_input(self.hass, user_input)
home-assistant   |   File "/config/custom_components/bmw_connected_drive/config_flow.py", line 42, in validate_input
home-assistant   |     await account.get_vehicles()
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 86, in get_vehicles
home-assistant   |     self.vehicles.append(MyBMWVehicle(self, vehicle_dict))
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle/vehicle.py", line 90, in __init__
home-assistant   |     self.update_state(vehicle_data)
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle/vehicle.py", line 106, in update_state
home-assistant   |     setattr(self, vehicle_attribute, cls.from_vehicle_data(vehicle_data))
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/bimmer_connected/models.py", line 29, in from_vehicle_data
home-assistant   |     parsed = cls._parse_vehicle_data(vehicle_data) or {}
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle/charging_profile.py", line 119, in _parse_vehicle_data
home-assistant   |     retval["preferred_charging_window"] = ChargingWindow(charging_profile["reductionOfChargeCurrent"])
home-assistant   | KeyError: 'reductionOfChargeCurrent'
```

**Comment by rikroe** [comment]
It seems those keys are only present at some times... Haven't figured it out yet...

**Comment by YeomansIII** [comment]
Is there any precedence in this codebase for having optional keys? Perhaps with a default if they are not returned from the API?
