### ISSUE TITLE
Error communicating with BMW API (Quota exceeded) 

### ISSUE THREAD

**Issue by plaxtika** [bimmerconnected/bimmer_connected#501]
### Describe the issue

Logger: homeassistant.config_entries
Source: config_entries.py:1089
First occurred: 14:32:12 (1 occurrences)
Last logged: 14:32:12

Config entry 'EMail' for bmw_connected_drive integration not ready yet: Error communicating with BMW API: Client error '403 Quota Exceeded' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v2/vehicles' For more information check: https://httpstatuses.com/403; Retrying in background

### Expected behavior

Is it only a connection Problem or a Failure ?

### Which Home Assistant version are you using?

2022.11.5

### What was the last working version of Home Assistant Core?

2022.11.5

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:1089
First occurred: 14:32:12 (1 occurrences)
Last logged: 14:32:12

Config entry 'EMail' for bmw_connected_drive integration not ready yet: Error communicating with BMW API: Client error '403 Quota Exceeded' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v2/vehicles' For more information check: https://httpstatuses.com/403; Retrying in background
```

**Comment by gerard33** [comment]
I had the same issue today, but it's working fine again. Can you check if the same applies for you?
I understood there was a generic issue today with the BMW app as well.

**Comment by plaxtika** [comment]
Today in the morning it was still broken - and now i watched, its back online. U r right 👍🏻

**Comment by plaxtika** [comment]
and now back unavailable :-/

**Comment by plaxtika** [comment]
`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: aiohttp.server
Source: custom_components/bmw_connected_drive/diagnostics.py:58
Integration: BMW Connected Drive
First occurred: 09:11:14 (3 occurrences)
Last logged: 10:39:31

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 211, in get
    data = await info[d_type.value](hass, config_entry)
  File "/config/custom_components/bmw_connected_drive/diagnostics.py", line 88, in async_get_config_entry_diagnostics
    await async_get_fingerprints(coordinator), TO_REDACT_DATA
  File "/config/custom_components/bmw_connected_drive/diagnostics.py", line 58, in async_get_fingerprints
    await coordinator.account.get_vehicles()
  File "/usr/local/lib/python3.10/site-packages/bimmer_connected/account.py", line 67, in get_vehicles
    vehicles_responses: List[httpx.Response] = [
  File "/usr/local/lib/python3.10/site-packages/bimmer_connected/account.py", line 68, in <listcomp>
    await client.get(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1751, in get
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1700, in _send_handling_redirects
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    await hook(response)
  File "/usr/local/lib/python3.10/site-packages/bimmer_connected/api/client.py", line 66, in raise_for_status_event_handler
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Quota Exceeded' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v2/vehicles'
For more information check: https://httpstatuses.com/403
`

**Comment by rikroe** [comment]
Looks similar to https://github.com/home-assistant/core/issues/78792, just on the next endpoint (the status per vehicle).

If so, the the quota blocking will block your whole account (i.e. also block the official app) and reset at 0:00 UTC.

You can try to disable automated polling (5 minute interval) in the integration'system option settings in HA.
Then create an automation that calls the `homeassistant.update_entity` service every 30 minutes.

**Comment by nottledim** [comment]
> Then create an automation that calls the homeassistant.update_entity service every 20 minutes.

Does it matter which entity?

**Comment by plaxtika** [comment]
I created the automation an update all entities. But only the sensors are now available but the buttons are not ?

**Comment by plaxtika** [comment]
Hm… and now all entities returned to unavailable. (Set the entity update to 30min)

**Comment by rikroe** [comment]
Did you disable the automatic polling (see https://github.com/home-assistant/core/issues/83128#issuecomment-1336194138)? 

With automatic polling disabled please reload the integration tomorrow morning (or anytime after 0:00 UTC).

**Comment by plaxtika** [comment]
> Did you disable the automatic polling (see [home-assistant/core#83128 (comment)](https://github.com/home-assistant/core/issues/83128#issuecomment-1336194138))?
> 
> With automatic polling disabled please reload the integration tomorrow morning (or anytime after 0:00 UTC).

I checked the checkbox right ? 
![9983583D-2D45-479D-9BD7-6A230D03355E](https://user-images.githubusercontent.com/35133439/205509455-98595234-bdc0-4f20-9658-30a2a6bd85ae.jpeg)

**Comment by uphillbattle** [comment]
@plaxtika No, it's the lowermost switch that shows if you click the three dots on the integration and then select System options (or whatever it's called in English and German). It disables automatic polling.

![image](https://user-images.githubusercontent.com/15340540/205630992-af85df02-7930-4fd7-84e6-0ffcd973820a.png)

**Comment by rikroe** [comment]
It seems that changing the API endpoints to the ones used by the latest MyBMW version (#509) solved the Quota exeeded issue.
I was able to check the vehicle status every minute for 2.5 hours - the old one would have cancelled after 2 hours (120 requests).

I have just released the changes with a new version (https://github.com/bimmerconnected/bimmer_connected/releases/tag/0.12.0) and will create a PR for Home Assistant.

**Comment by rikroe** [comment]
The PR got merged into HA and released with 2023.1.1, so please test this out. The 5 minute interval should be ok again.

**Comment by sweetw0r** [comment]
How do I get this working in HA? Kept getting 403

**Comment by rikroe** [comment]
Which HA version are you using? Are you still using the custom component?

**Comment by sweetw0r** [comment]
> Which HA version are you using? Are you still using the custom component?

@rikroe yes

**Comment by rikroe** [comment]
Both the latest custom component and HA default component should be fine and don't produce any quota issues for rest of world when triggered every five minutes.
