### ISSUE TITLE
Find Vehicle Not Working from italy with conventional vehicle.

### ISSUE THREAD

**Issue by lamerjack** [bimmerconnected/bimmer_connected#524]
### Describe the issue

bimmerconnected vehiclefinder myaddrress@host.it MyPassword rest_of_world mycarVIN
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.api.authentication:Authenticating with MyBMW flow for North America & Rest of World.
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-ucs/v1/presentation/oauth/config "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://customer.bmwgroup.com/gcdm/oauth/authenticate "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://customer.bmwgroup.com/gcdm/oauth/authenticate "HTTP/1.1 302 Found"
DEBUG:httpx._client:HTTP Request: POST https://customer.bmwgroup.com/gcdm/oauth/token "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles/state "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/WBA2B11090V687244/vehicle-finder "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:getting remote service status for '126a24f5-f560-4374-a729-1f363d00d44f'
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventStatus?eventId=126a24f5-f560-4374-a729-1f363d00d44f "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:current state of '126a24f5-f560-4374-a729-1f363d00d44f' is: PENDING
DEBUG:bimmer_connected.vehicle.remote_services:getting remote service status for '126a24f5-f560-4374-a729-1f363d00d44f'
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventStatus?eventId=126a24f5-f560-4374-a729-1f363d00d44f "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:current state of '126a24f5-f560-4374-a729-1f363d00d44f' is: PENDING
DEBUG:bimmer_connected.vehicle.remote_services:getting remote service status for '126a24f5-f560-4374-a729-1f363d00d44f'
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventStatus?eventId=126a24f5-f560-4374-a729-1f363d00d44f "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:current state of '126a24f5-f560-4374-a729-1f363d00d44f' is: PENDING
DEBUG:bimmer_connected.vehicle.remote_services:getting remote service status for '126a24f5-f560-4374-a729-1f363d00d44f'
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventStatus?eventId=126a24f5-f560-4374-a729-1f363d00d44f "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:current state of '126a24f5-f560-4374-a729-1f363d00d44f' is: PENDING
DEBUG:bimmer_connected.vehicle.remote_services:getting remote service status for '126a24f5-f560-4374-a729-1f363d00d44f'
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventStatus?eventId=126a24f5-f560-4374-a729-1f363d00d44f "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:current state of '126a24f5-f560-4374-a729-1f363d00d44f' is: PENDING
DEBUG:bimmer_connected.vehicle.remote_services:getting remote service status for '126a24f5-f560-4374-a729-1f363d00d44f'
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventStatus?eventId=126a24f5-f560-4374-a729-1f363d00d44f "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:current state of '126a24f5-f560-4374-a729-1f363d00d44f' is: PENDING
DEBUG:bimmer_connected.vehicle.remote_services:getting remote service status for '126a24f5-f560-4374-a729-1f363d00d44f'
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventStatus?eventId=126a24f5-f560-4374-a729-1f363d00d44f "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:current state of '126a24f5-f560-4374-a729-1f363d00d44f' is: EXECUTED
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventPosition?eventId=126a24f5-f560-4374-a729-1f363d00d44f "HTTP/1.1 400 Bad Request"
Traceback (most recent call last):
  File "/home/rootto/.local/bin/bimmerconnected", line 8, in <module>
    sys.exit(main())
  File "/home/rootto/.local/lib/python3.9/site-packages/bimmer_connected/cli.py", line 356, in main
    loop.run_until_complete(args.func(args))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/rootto/.local/lib/python3.9/site-packages/bimmer_connected/cli.py", line 211, in vehicle_finder
    status = await vehicle.remote_services.trigger_remote_vehicle_finder()
  File "/home/rootto/.local/lib/python3.9/site-packages/bimmer_connected/vehicle/remote_services.py", line 309, in trigger_remote_vehicle_finder
    result = await self._get_event_position(status.event_id)
  File "/home/rootto/.local/lib/python3.9/site-packages/bimmer_connected/vehicle/remote_services.py", line 323, in _get_event_position
    response = await client.post(
  File "/home/rootto/.local/lib/python3.9/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/home/rootto/.local/lib/python3.9/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/rootto/.local/lib/python3.9/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/home/rootto/.local/lib/python3.9/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/rootto/.local/lib/python3.9/site-packages/httpx/_client.py", line 1706, in _send_handling_redirects
    raise exc
  File "/home/rootto/.local/lib/python3.9/site-packages/httpx/_client.py", line 1688, in _send_handling_redirects
    await hook(response)
  File "/home/rootto/.local/lib/python3.9/site-packages/bimmer_connected/api/client.py", line 69, in raise_for_status_event_handler
    response.raise_for_status()
  File "/home/rootto/.local/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventPosition?eventId=126a24f5-f560-4374-a729-1f363d00d44f'
For more information check: https://httpstatuses.com/400

### Expected behavior

Get car coordinates

### Which Home Assistant version are you using?

i dont use home assistant

### What was the last working version of Home Assistant Core?

i dont use home assistant

### What is your region?

Rest of world

### MyBMW website

- [ ] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [ ] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Output of bimmer_connected fingerprint

```txt
Fingerprint.json

{
    "capabilities": {
        "a4aType": "USB_ONLY",
        "digitalKey": {
            "bookedServicePackage": "NONE",
            "state": "NOT_AVAILABLE",
            "vehicleSoftwareUpgradeRequired": false
        },
        "horn": true,
        "isBmwChargingSupported": false,
        "isCarSharingSupported": false,
        "isChargeNowForBusinessSupported": false,
        "isChargingHistorySupported": false,
        "isChargingHospitalityEnabled": false,
        "isChargingLoudnessEnabled": false,
        "isChargingPlanSupported": false,
        "isChargingPowerLimitEnabled": false,
        "isChargingSettingsEnabled": false,
        "isChargingTargetSocEnabled": false,
        "isClimateTimerWeeklyActive": false,
        "isCustomerEsimSupported": false,
        "isDCSContractManagementSupported": false,
        "isDataPrivacyEnabled": false,
        "isEasyChargeEnabled": false,
        "isEvGoChargingSupported": false,
        "isMiniChargingSupported": false,
        "isNonLscFeatureEnabled": true,
        "isPersonalPictureUploadSupported": false,
        "isRemoteEngineStartSupported": false,
        "isRemoteHistoryDeletionSupported": false,
        "isRemoteHistorySupported": true,
        "isRemoteParkingSupported": false,
        "isRemoteServicesActivationRequired": false,
        "isRemoteServicesBookingRequired": false,
        "isScanAndChargeSupported": false,
        "isSustainabilityAccumulatedViewEnabled": false,
        "isSustainabilitySupported": false,
        "isWifiHotspotServiceSupported": false,
        "lights": true,
        "lock": true,
        "remoteChargingCommands": {},
        "sendPoi": true,
        "specialThemeSupport": [],
        "unlock": true,
        "vehicleFinder": true,
        "vehicleStateSource": "A4A"
    },
    "state": {
        "checkControlMessages": [
            {
                "severity": "LOW",
                "type": "ENGINE_OIL"
            }
        ],
        "climateTimers": [
            {
                "departureTime": {
                    "hour": 7,
                    "minute": 0
                },
                "isWeeklyTimer": false,
                "timerAction": "DEACTIVATE",
                "timerWeekDays": []
            },
            {
                "departureTime": {
                    "hour": 7,
                    "minute": 0
                },
                "isWeeklyTimer": true,
                "timerAction": "DEACTIVATE",
                "timerWeekDays": [
                    "MONDAY"
                ]
            },
            {
                "departureTime": {
                    "hour": 7,
                    "minute": 0
                },
                "isWeeklyTimer": true,
                "timerAction": "DEACTIVATE",
                "timerWeekDays": [
                    "MONDAY"
                ]
            }
        ],
        "driverPreferences": {
            "lscPrivacyMode": "OFF"
        },
        "isLeftSteering": true,
        "isLscSupported": false,
        "lastFetched": "2023-04-03T08:38:25.100Z",
        "lastUpdatedAt": "0001-01-01T00:00:00Z",
        "requiredServices": []
    }
}
state.json

{
    "capabilities": {
        "a4aType": "USB_ONLY",
        "digitalKey": {
            "bookedServicePackage": "NONE",
            "state": "NOT_AVAILABLE",
            "vehicleSoftwareUpgradeRequired": false
        },
        "horn": true,
        "isBmwChargingSupported": false,
        "isCarSharingSupported": false,
        "isChargeNowForBusinessSupported": false,
        "isChargingHistorySupported": false,
        "isChargingHospitalityEnabled": false,
        "isChargingLoudnessEnabled": false,
        "isChargingPlanSupported": false,
        "isChargingPowerLimitEnabled": false,
        "isChargingSettingsEnabled": false,
        "isChargingTargetSocEnabled": false,
        "isClimateTimerWeeklyActive": false,
        "isCustomerEsimSupported": false,
        "isDCSContractManagementSupported": false,
        "isDataPrivacyEnabled": false,
        "isEasyChargeEnabled": false,
        "isEvGoChargingSupported": false,
        "isMiniChargingSupported": false,
        "isNonLscFeatureEnabled": true,
        "isPersonalPictureUploadSupported": false,
        "isRemoteEngineStartSupported": false,
        "isRemoteHistoryDeletionSupported": false,
        "isRemoteHistorySupported": true,
        "isRemoteParkingSupported": false,
        "isRemoteServicesActivationRequired": false,
        "isRemoteServicesBookingRequired": false,
        "isScanAndChargeSupported": false,
        "isSustainabilityAccumulatedViewEnabled": false,
        "isSustainabilitySupported": false,
        "isWifiHotspotServiceSupported": false,
        "lights": true,
        "lock": true,
        "remoteChargingCommands": {},
        "sendPoi": true,
        "specialThemeSupport": [],
        "unlock": true,
        "vehicleFinder": true,
        "vehicleStateSource": "A4A"
    },
    "state": {
        "checkControlMessages": [
            {
                "severity": "LOW",
                "type": "ENGINE_OIL"
            }
        ],
        "climateTimers": [
            {
                "departureTime": {
                    "hour": 7,
                    "minute": 0
                },
                "isWeeklyTimer": false,
                "timerAction": "DEACTIVATE",
                "timerWeekDays": []
            },
            {
                "departureTime": {
                    "hour": 7,
                    "minute": 0
                },
                "isWeeklyTimer": true,
                "timerAction": "DEACTIVATE",
                "timerWeekDays": [
                    "MONDAY"
                ]
            },
            {
                "departureTime": {
                    "hour": 7,
                    "minute": 0
                },
                "isWeeklyTimer": true,
                "timerAction": "DEACTIVATE",
                "timerWeekDays": [
                    "MONDAY"
                ]
            }
        ],
        "driverPreferences": {
            "lscPrivacyMode": "OFF"
        },
        "isLeftSteering": true,
        "isLscSupported": false,
        "lastFetched": "2023-04-03T08:38:25.100Z",
        "lastUpdatedAt": "0001-01-01T00:00:00Z",
        "requiredServices": []
    }
}
```

**Comment by lamerjack** [comment]
a little update.
COMMANDS THAT WORKS:
status,fingerprint,lightflash,horn,image,sendpoi,

COMMANDS THAT DOESNT WORKS
vehiclefinder sendpoi_from_address (i dont know what it should do, i suppose add a poi from local position, so seems that issue is related to read the car position)

COMMANDS THAT ARE NOT SUPPORTED (is not an electric car)
chargingsettings,chargingprofile,charge

**Comment by rikroe** [comment]
What model year is your car? On pre 2014 cars you need to be max. 2km away (at least supply the location via CLI).

See https://bimmer-connected.readthedocs.io/en/latest/cli.html#vehiclefinder

**Comment by lamerjack** [comment]
Thank you very much!
My car is a Serie 2 Active Tourer (F45) is from 2016.
I just need to add my position and the command works (also if i'm far than 2km)
i just get these 2 wanrings:
WARNING:bimmer_connected.utils:DeprecationWarning:/home/rootto/bimmer_connected/bimmer_connected/cli.py:213: 'VehicleStatus.gps_position' is deprecated. Please change to 'vehicle.vehicle_location.location'.
WARNING:bimmer_connected.utils:DeprecationWarning:/home/rootto/bimmer_connected/bimmer_connected/cli.py:213: 'VehicleStatus.gps_heading' is deprecated. Please change to 'vehicle.vehicle_location.heading'.
But i get car position!
Thank you very much!!!
