### ISSUE TITLE
Getting Client authentication failed when attempting to connect (using the latest version)

### ISSUE THREAD

**Issue by johnflan** [bimmerconnected/bimmer_connected#538]
### Describe the issue

MyBMW API error: HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/bimmer_connected/api/authentication.py", line 380, in raise_for_status_event_handler
    response.raise_for_status()
  File "/home/user/.local/lib/python3.9/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://customer.bmwgroup.com/gcdm/oauth/authenticate'
For more information check: https://httpstatuses.com/401

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/bin/bimmerconnected", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/bimmer_connected/cli.py", line 356, in main
    loop.run_until_complete(args.func(args))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.9/site-packages/bimmer_connected/cli.py", line 138, in get_status
    await account.get_vehicles()
  File "/home/user/.local/lib/python3.9/site-packages/bimmer_connected/account.py", line 93, in get_vehicles
    await self._init_vehicles()
  File "/home/user/.local/lib/python3.9/site-packages/bimmer_connected/account.py", line 72, in _init_vehicles
    vehicles_responses: List[httpx.Response] = [
  File "/home/user/.local/lib/python3.9/site-packages/bimmer_connected/account.py", line 73, in <listcomp>
    await client.get(
  File "/home/user/.local/lib/python3.9/site-packages/httpx/_client.py", line 1751, in get
    return await self.request(
  File "/home/user/.local/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/user/.local/lib/python3.9/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/home/user/.local/lib/python3.9/site-packages/httpx/_client.py", line 1639, in _send_handling_auth
    request = await auth_flow.__anext__()
  File "/home/user/.local/lib/python3.9/site-packages/bimmer_connected/api/authentication.py", line 80, in async_auth_flow
    await self.login()
  File "/home/user/.local/lib/python3.9/site-packages/bimmer_connected/api/authentication.py", line 118, in login
    token_data = await self._login_row_na()
  File "/home/user/.local/lib/python3.9/site-packages/bimmer_connected/api/authentication.py", line 170, in _login_row_na
    response = await client.post(
  File "/home/user/.local/lib/python3.9/site-packages/httpx/_client.py", line 1842, in post
    return await self.request(
  File "/home/user/.local/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/user/.local/lib/python3.9/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/home/user/.local/lib/python3.9/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/user/.local/lib/python3.9/site-packages/httpx/_client.py", line 1700, in _send_handling_redirects
    raise exc
  File "/home/user/.local/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    await hook(response)
  File "/home/user/.local/lib/python3.9/site-packages/bimmer_connected/api/authentication.py", line 382, in raise_for_status_event_handler
    await handle_httpstatuserror(ex, log_handler=_LOGGER)
  File "/home/user/.local/lib/python3.9/site-packages/bimmer_connected/api/utils.py", line 79, in handle_httpstatuserror
    raise _ex_to_raise(_err_message) from ex
bimmer_connected.models.MyBMWAuthError: HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)

### Expected behavior

The client should connect

### Which Home Assistant version are you using?

not using HA

### What is your region?

Rest of world

### MyBMW website

- [ ] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [ ] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by martingrassl** [comment]
I got the same issue and could fix it. Try to login to the myBMW portal and you will get a notification that you have to change your password. Do it and set the new password in your requests, it should work fine.

**Comment by johnflan** [comment]
You are totally right, that worked. 

It would be nice if a more instructive error was available, but the bug itself should be closed
