### ISSUE TITLE
HTTPStatusError: Failed to fetch Vehicle Features

### ISSUE THREAD

**Issue by wozz** [bimmerconnected/bimmer_connected#539]
### Describe the issue

I have two vehicles in my account, one of which is quite old and doesn't really support anything of value via the app/api. However, there doesn't seem to be a way to skip a vehicle as unsupported while still supporting others.

The logs I've attached are from running the cli status command.

If I modify the code to skip the unsupported VIN, everything works fine.

### Expected behavior

I would expect to be able to still load my supported vehicle details, and either skip the unsupported vehicle or show the few details available and that it's unsupported.

### Which Home Assistant version are you using?

core-2023.6.0

### What is your region?

North America

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [X] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Anything in the logs that might be useful for us?

```txt
DEBUG:httpcore:http11.receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore:http11.receive_response_body.complete
DEBUG:httpcore:http11.response_closed.started
DEBUG:httpcore:http11.response_closed.complete
ERROR:bimmer_connected.api.client:MyBMW API error: HTTPStatusError: Failed to fetch Vehicle Features.
DEBUG:httpcore:connection.close.started
DEBUG:httpcore:connection.close.complete
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/bimmer_connected/api/client.py", line 72, in raise_for_status_event_handler
    response.raise_for_status()
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://cocoapi.bmwgroup.us/eadrax-vcs/v4/vehicles/state?apptimezone=1200.0&appDateTime=1686193717192'
For more information check: https://httpstatuses.com/500

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/bin/bimmerconnected", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/bimmer_connected/cli.py", line 356, in main
    loop.run_until_complete(args.func(args))
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/bimmer_connected/cli.py", line 138, in get_status
    await account.get_vehicles()
  File "/srv/homeassistant/lib/python3.11/site-packages/bimmer_connected/account.py", line 98, in get_vehicles
    state_response = await client.get(
                     ^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1703, in _send_handling_redirects
    raise exc
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    await hook(response)
  File "/srv/homeassistant/lib/python3.11/site-packages/bimmer_connected/api/client.py", line 74, in raise_for_status_event_handler
    await handle_httpstatuserror(ex, log_handler=_LOGGER)
  File "/srv/homeassistant/lib/python3.11/site-packages/bimmer_connected/api/utils.py", line 79, in handle_httpstatuserror
    raise _ex_to_raise(_err_message) from ex
bimmer_connected.models.MyBMWAPIError: HTTPStatusError: Failed to fetch Vehicle Features.
```

**Comment by rikroe** [comment]
Could you provide a fingerprint from the CLI?
Maybe there is some information in the vehicle overview on which we can ignore vehicles.

**Comment by rikroe** [comment]
Adjusting the library to be more resilient with errors is something I have planned, but not found the time to look into yet.
My car is even older than yours and still works.

One thing is weird with your request: your `apptimezone` parameter is `1200.0`, meaning UTC+20 (which doesn't exist). Could you double check the time zone of your device?

**Comment by wozz** [comment]
everything works fine for my other car though. in the meantime, I have removed the unsupported car from my account as a workaround.

assuming timezones would wrap around, UTC+20 sounds about right since I'm in EDT, which is UTC-4
