### ISSUE TITLE
500 Error on sendpoi from CLI

### ISSUE THREAD

**Issue by ryanbuckner** [bimmerconnected/bimmer_connected#559]
### Describe the issue

Using the CLI sendpoi results in a 500 error as below. This started a few weeks ago.  Other commands are still working. 

command sent:  
`bimmerconnected sendpoi --name "555 Main Street" example@gmail.com password@ north_america myVin lat long`
result:
`bimmer_connected.models.MyBMWAPIError: HTTPStatusError: {"statusCode":500,"message":"Failed Dependency"}`

Full error: 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/bimmerconnected", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/cli.py", line 356, in main
    loop.run_until_complete(args.func(args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/cli.py", line 292, in send_poi
    await vehicle.remote_services.trigger_send_poi(poi_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/vehicle/remote_services.py", line 299, in trigger_send_poi
    return await self.trigger_remote_service(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/vehicle/remote_services.py", line 117, in trigger_remote_service
    response = await client.post(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1703, in _send_handling_redirects
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    await hook(response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/api/client.py", line 74, in raise_for_status_event_handler
    await handle_httpstatuserror(ex, log_handler=_LOGGER)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/api/utils.py", line 83, in handle_httpstatuserror
    raise _ex_to_raise(_err_message) from ex
bimmer_connected.models.MyBMWAPIError: HTTPStatusError: {"statusCode":500,"message":"Failed Dependency"}
```

### Expected behavior

Address should be sent to my BMW as a point of interest

### Which Home Assistant version are you using?

cli

### What was the last working version of Home Assistant Core?

na

### What is your region?

North America

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Anything in the logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/bimmerconnected", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/cli.py", line 356, in main
    loop.run_until_complete(args.func(args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/cli.py", line 292, in send_poi
    await vehicle.remote_services.trigger_send_poi(poi_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/vehicle/remote_services.py", line 299, in trigger_send_poi
    return await self.trigger_remote_service(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/vehicle/remote_services.py", line 117, in trigger_remote_service
    response = await client.post(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1703, in _send_handling_redirects
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    await hook(response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/api/client.py", line 74, in raise_for_status_event_handler
    await handle_httpstatuserror(ex, log_handler=_LOGGER)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bimmer_connected/api/utils.py", line 83, in handle_httpstatuserror
    raise _ex_to_raise(_err_message) from ex
bimmer_connected.models.MyBMWAPIError: HTTPStatusError: {"statusCode":500,"message":"Failed Dependency"}
```

**Comment by ryanbuckner** [comment]
fingerprint:  

`
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/certifi/cacert.pem'
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/certifi/cacert.pem'
DEBUG:bimmer_connected.api.authentication:Authenticating with MyBMW flow for North America & Rest of World.
INFO:httpx:HTTP Request: GET https://cocoapi.bmwgroup.us/eadrax-ucs/v1/presentation/oauth/config "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://login.bmwusa.com/gcdm/oauth/authenticate "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://login.bmwusa.com/gcdm/oauth/authenticate?interaction-id=21e8f9cd-05a9-4c13-b06b-caf971a79140&client-version=android%28TQ2A.230405.003.B2%29%3Bbmw%3B3.3.1%2822418%29%3Bna "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: POST https://login.bmwusa.com/gcdm/oauth/token "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://cocoapi.bmwgroup.us/eadrax-vcs/v4/vehicles "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://cocoapi.bmwgroup.us/eadrax-vcs/v4/vehicles "HTTP/1.1 200 OK"
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/certifi/cacert.pem'
INFO:httpx:HTTP Request: GET https://cocoapi.bmwgroup.us/eadrax-vcs/v4/vehicles/state?apptimezone=1200.0&appDateTime=1692556184124 "HTTP/1.1 200 OK"
fingerprint of the vehicles written to /Users/ryanbuckner/vehicle_fingerprint/2023-08-20_14-29-44

`

**Comment by rikroe** [comment]
This should be fixed with [0.13.9](https://github.com/bimmerconnected/bimmer_connected/releases/tag/0.13.9), please upgrade and try again.

**Comment by ryanbuckner** [comment]
Thanks for the quick reply. I upgraded to 0.13.9 and receive the same error. Do I need to do anything else to upgrade the CLI or does that upgrade with the pip? 

```
ryanbuckner@Ryans-Air bin % pip3 list
Package          Version
---------------- ---------
altgraph         0.17.2
anyio            3.7.1
bimmer-connected 0.13.9
certifi          2023.7.22
exceptiongroup   1.1.3
future           0.18.2
h11              0.14.0
httpcore         0.17.3
httpx            0.24.1
idna             3.4
macholib         1.15.2
pip              23.2.1
pycryptodome     3.18.0
PyJWT            2.8.0
setuptools       58.0.4
six              1.15.0
sniffio          1.3.0
wheel            0.37.0

```

**Comment by rikroe** [comment]
Please try to remove the library by executing `pip3 uninstall bimmer_connected` multiple times.
I remember another user whose pip freeze showed the latest version, but the command line was pointing to another installation (venv or user dir).

**Comment by ryanbuckner** [comment]
I uninstalled a number of times and then reinstalled.  Same error message.

**Comment by rikroe** [comment]
Yep, that sounds like the issue. It seems that you once installed bimmer_connected into the system Python (maybe even with `sudo`).

Try (without or with `sudo`): `/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip uninstall bimmer_connected`

**Comment by ryanbuckner** [comment]
Once, uninstalled and reinstalled , where should I be running the command line?

**Comment by ryanbuckner** [comment]
Thank you. Working now!
