### ISSUE TITLE
GLIBC_2.33 missing

### ISSUE THREAD

**Issue by FilipDem** [bimmerconnected/bimmer_connected#636]
### Describe the issue

When upgrading bimmer_connected to tha latest version on my Raspberry Pi Bullseye, I got the error "ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/lib/python3.9/dist-packages/cryptography/hazmat/bindings/_rust.abi3.so)".

With Bullseye 2.31 is used... Is there way without upgrading the complete OS?

### Expected behavior

Would like to get it working under Bullseye;

### Which Home Assistant version are you using?

(using Domoticz)

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.
- [ ] I have a Toyota Supra vehicle linked to my account.

### Output of bimmer_connected fingerprint

```txt
Traceback (most recent call last):
  File "/usr/local/bin/bimmerconnected", line 5, in <module>
    from bimmer_connected.cli import main
  File "/usr/local/lib/python3.9/dist-packages/bimmer_connected/cli.py", line 14, in <module>
    from bimmer_connected.account import MyBMWAccount
  File "/usr/local/lib/python3.9/dist-packages/bimmer_connected/account.py", line 9, in <module>
    from bimmer_connected.api.authentication import MyBMWAuthentication
  File "/usr/local/lib/python3.9/dist-packages/bimmer_connected/api/authentication.py", line 13, in <module>
    import jwt
  File "/usr/local/lib/python3.9/dist-packages/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/usr/local/lib/python3.9/dist-packages/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/usr/local/lib/python3.9/dist-packages/jwt/algorithms.py", line 12, in <module>
    from .utils import (
  File "/usr/local/lib/python3.9/dist-packages/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
    from cryptography.exceptions import UnsupportedAlgorithm, _Reasons
  File "/usr/local/lib/python3.9/dist-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/lib/python3.9/dist-packages/cryptography/hazmat/bindings/_rust.abi3.so)
```

**Comment by rikroe** [comment]
This is an issue for/with `cryptography`. You'll need to check there what to do about it, sorry.

**Comment by FilipDem** [comment]
Ok thank, but this helped me way forward.
I noticed and I made a mistake by installing cryptography with 'pip3'.
While installing it with 'apt', it went to the right version of my OS.
Thanks!
